# Site
repository: XiangGuo/xig84github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: XiangGuo
title: Senior Network System Administrator
email: xig84@pitt.edu
website: www.github.com/xig84.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  Xig84
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: Guo Xiang
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: None
        # link_text: boringcompany.com
        description: | # this will include new lines to allow paragraphs
            So far I have no working experience in an Internet company.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Central South University
        caption: 2019 - 2023
        sub_title: BE Transportation Engineer
        quote: >
            Central South University is a Chinese university located in Changsha, Hunan Province.
        description: | # this will include new lines to allow paragraphs
          During my undergraduate studies, I came into contact with transportation big data, intelligent transportation, etc., which made me interested in computers.
      - layout: left
        title: University of Pittsburgh
        caption: 2023 - present
        sub_title: Ms Information Science
        quote: >
            The University of Pittsburgh is an American university located in Pittsburgh, Pennsylvania.
       description: In this University, I started to study things that more interested me.
      
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in big data and software engineering some of my other interests and hobbies are:
      - philosophy
      - Gaming
      - Running
      - Reading novels

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
